spring:
  application:
    name: lecture
  datasource:
    url: jdbc:h2:mem:test
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
   database: h2
   generate-ddl: true
   hibernate:
     ddl-auto: create
   properties:
     hibernate:
       show_sql: true
       format_sql: true
   defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2